baseapp/urls.py
from django.urls import path
from . import views

app_name='baseapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('baseapp/about/',views.about, name='about'),
    path('baseapp/portfolio_1/',views.portfolio_1, name='portfolio_1'),
    path('baseapp/portfolio_2/',views.portfolio_2, name='portfolio_2'),
    path('baseapp/portfolio_3/',views.portfolio_3, name='portfolio_3'),
    path('baseapp/portfolio_4/',views.portfolio_4, name='portfolio_4'),
    path('baseapp/portfolio_0/',views.portfolio_0, name='portfolio_0'),
    path('baseapp/faq/',views.faq, name='faq'),

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name ='common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

community/urls.py
from django.urls import path
from . import views

app_name='community'

urlpatterns = [
    path("", views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/',views.answer_create, name='answer_create'),
    path('question/create/',views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer, name='comment_delete_answer'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from community import views
from django.conf.urls.static import static
from django.conf import settings


# from community import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("community/", include('community.urls')),
    path('common/', include('common.urls')),
    path('qq', views.index, name='index1'),
    path('', include('baseapp.urls'), name='index'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    subject=models.CharField(max_length=200)
    content=models.TextField()
    image_file=models.ImageField(max_length=100,blank=True, null=True)
    create_date=models.DateTimeField()
    modify_date=models.DateTimeField(null=True,blank=True)
    class Meta:
        managed = False
        db_table = 'community_question'

class Answer(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    question=models.ForeignKey(Question, on_delete=models.CASCADE)
    content=models.TextField()
    create_date=models.DateTimeField()
    modify_date=models.DateTimeField(null=True,blank=True)
    class Meta:
        managed = False
        db_table = 'community_answer'


class Comment(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    content=models.TextField()
    create_date=models.DateTimeField()
    modify_date=models.DateTimeField(null=True,blank=True)
    question=models.ForeignKey(Question, null=True,blank=True, on_delete=models.CASCADE)
    answer=models.ForeignKey(Answer, null=True,blank=True, on_delete=models.CASCADE)
    class Meta:
        managed = False
        db_table = 'community_comment'

community/forms.py
from django import forms
from community.models import Question, Answer, Comment

class QuestionForm(forms.ModelForm):
    class Meta:
        model=Question
        fields=['subject','content','image_file']
        # widgets={
        #     'subject': forms.TextInput(attrs={'class':'form-control'}),
        #     'content': forms.Textarea(attrs={'class':'form-control', 'rows': 10})
        #     'image_file: forms.ImageFile(attrs={'class':'form-control'})
        # }

        labels={
            'subject': '제목',
            'content': '내용',
            'image_file': '이미지'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model=Answer
        fields=['content']
        labels={
            'content': '답변내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['content']
        labels={
            'content': '댓글내용',
        }

community/views.py
from django.shortcuts import render,get_object_or_404,redirect,resolve_url
from django.http import HttpResponse
from .models import Question, Answer, Comment
from django.utils import timezone
from .forms import QuestionForm, AnswerForm, CommentForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q, Count

# Create your views here.

def main(request):
    return render(request, 'main.html')

def index(request):
    page=request.GET.get('page','1')
    kw=request.GET.get('kw','')
    so=request.GET.get('so','recent')

    if so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  
        question_list = Question.objects.order_by('-create_date')

    if kw:
        question_list=question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()
    paginator=Paginator(question_list,10)
    page_obj=paginator.get_page(page)

    context={'question_list':page_obj, 'page':page, 'kw':kw, 'so':so}
    return render(request, 'community/question_list.html', context)

def detail(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    question = Question.objects.get(id=question_id)
    context={'question':question}
    return render(request, 'community/question_detail.html', context)

# 질문 게시판 관련
@login_required(login_url='common:login')
def question_create(request):
    if request.method =='POST':
        form=QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            question=form.save(commit=False)
            question.author=request.user
            question.create_date=timezone.now()
            question.save()
            return redirect('community:index')
    else:
        form=QuestionForm()
    return render(request, 'community/question_form.html', {'form': form})

@login_required(login_url='common:login')
def question_modify(request,question_id):
    question=get_object_or_404(Question,pk=question_id)

    if request.user != question.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('community:detail', question_id=question.id)

    if request.method =='POST':
        form=QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question=form.save(commit=False)
            question.author=request.user
            question.modify_date=timezone.now()
            question.save()
            return redirect('community:detail',question_id=question.id)
    else:
        form=QuestionForm(instance=question)
    context={'form':form}
    return render(request, 'community/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request,question_id):
    question=get_object_or_404(Question,pk=question_id)

    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('community:detail', question_id=question.id)
    question.delete()
    return redirect('community:index')

# 질문에 대한 답변게시판 관련
@login_required(login_url='common:login')
def answer_create(request,question_id):
    question=get_object_or_404(Question,pk=question_id)

    if request.method =='POST':
        form=AnswerForm(request.POST)
        if form.is_valid():
            answer=form.save(commit=False)
            answer.author=request.user
            answer.create_date=timezone.now()
            answer.question=question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('community:detail',question_id=question.id),answer.id))
    else:
        form=AnswerForm()
    context={'question':question, 'form':form}
    return render(request, 'community/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request,answer_id):
    answer=get_object_or_404(Answer,pk=answer_id)

    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('community:detail', question_id=answer.question.id)

    if request.method =='POST':
        form=AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer=form.save(commit=False)
            answer.author=request.user
            answer.modify_date=timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('community:detail',question_id=answer.question.id),answer.id))
    else:
        form=AnswerForm(instance=answer)
    context={'answer':answer,'form':form}
    return render(request, 'community/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request,answer_id):
    answer=get_object_or_404(Answer,pk=answer_id)

    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다.')
    else:
        answer.delete()
    return redirect('community:detail', question_id=answer.question.id)

# 질문게시글 댓글 기능
@login_required(login_url='common:login')
def comment_create_question(request,question_id):
    question=get_object_or_404(Question,pk=question_id)

    if request.method =='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.create_date=timezone.now()
            comment.question=question
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('community:detail',question_id=comment.question.id),comment.id))
    else:
        form=CommentForm()
    context={'form':form}
    return render(request, 'community/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_question(request,comment_id):
    comment=get_object_or_404(Comment,pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('community:detail', question_id=comment.question.id)

    if request.method =='POST':
        form=CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.modify_date=timezone.now()
            comment.save()

            return redirect('{}#comment_{}'.format(
                resolve_url('community:detail',question_id=comment.question.id),comment.id))
    else:
        form=CommentForm(instance=comment)
    context={'form':form}
    return render(request, 'community/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request,comment_id):
    comment=get_object_or_404(Comment,pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '삭제 권한이 없습니다.')
    else:
        comment.delete()
    return redirect('community:detail', question_id=comment.question.id)

# 답변게시글 댓글 기능
@login_required(login_url='common:login')
def comment_create_answer(request,answer_id):
    answer=get_object_or_404(Answer,pk=answer_id)

    if request.method =='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.create_date=timezone.now()
            comment.answer=answer
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('community:detail',question_id=comment.answer.question.id),comment.id))
    else:
        form=CommentForm()
    context={'form':form}
    return render(request,'community/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_answer(request,comment_id):
    comment=get_object_or_404(Comment,pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('community:detail', question_id=comment.answer.question.id)

    if request.method =='POST':
        form=CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.modify_date=timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('community:detail',question_id=comment.answer.question.id),comment.id))
    else:
        form=CommentForm(instance=comment)
    context={'form':form}
    return render(request, 'community/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request,comment_id):
    comment=get_object_or_404(Comment,pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('community:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('community:detail', question_id=comment.answer.question.id)

templates/community/answer_form.html
{% extends 'base.html' %}
{% block content %}
{% include "navbar.html" %}

<div class="container-fluid my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
        <label for="content">답변 내용</label>
        <textarea class="form-control" name="content" id="content" 
            rows="10"> {{form.content.value|default_if_none:''}}
        </textarea>
    </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/community/comment_form.html
{% extends 'base.html' %}
{% block content %}
{% include "navbar.html" %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"> 
                <small>질문 등록</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url 'baseapp:index' %}">Home</a>
                </li>
                <li class="active" >질문등록</li>
            </ol>
        </div>
    </div>
</div>

<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글 등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
        <label for="content">댓글 내용</label>
        <textarea class="form-control" name="content" id="content" 
            rows="3"> {{form.content.value|default_if_none:''}}
        </textarea>
    </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/community/question_detail.html
{% extends 'base.html' %}
{% load community_filter %}
{% block content %}
{% include "navbar.html" %}

<div class="container my-1">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Q&A
                <small>Questions & Answers </small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url 'baseapp:index' %}">Home</a>
                </li>
                <li class="active"><a href="{% url 'community:index' %}" style="color: rgba(79, 76, 76, 0.749);">질문과 답변
                        리스트 </a></li>
            </ol>
        </div>
    </div>
</div>
<div class="container my-1" style="width: 80%;">
    <div class="row text-center">
        <div class="col-lg-12" style="background-color: aliceblue; border-radius: 20px;">
            <br>
            <h4 class="border-bottom"><small>질문 제목:</small><u> {{question.subject}} </u></h4>
            <div class="card-body">
                <div class="row">
                    <div class="card-text" id="content" style="float:center;  color: #191919d4; font-size: 14px;">
                        {{question.content|mark }}
                    </div>
                    {% if question.image_file %}
                    <div style="margin-top: 15px; margin-bottom: -10px;">
                        <img src="{{question.image_file.url}}" width="300" style="align-content:left;">
                    </div>
                    {%endif%}
                </div>
                <div class="d-flex justify-content-end">
                    {% if question.modify_date %}
                    <div class="badge badge-light p-2 text-left comment mr-1">
                        <div>modified at</div>
                        <div>{{question.modify_date}}</div>
                    </div>
                    {% endif %}
                    <div class="badge badge-light p2 text-left comment ml-1" style="background-color: #8b99a0;">
                        <div>{{question.author.username}}</div>
                        <div>{{question.create_date}}</div>
                    </div>
                </div>
                {% if request.user == question.author %}
                <div class="my-1">
                    <a href="{% url 'community:question_modify' question.id %}"
                        class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{% url 'community:question_delete' question.id %}">삭제</a>
                </div>
                {% endif %}
            </div>

        </div>
    </div>
    <h5 class="border-bottom" style="margin-left: 15px;">
        <i> {{question.answer_set.count}}개의 답변이 있습니다.</i>
    </h5>
</div>
</div>

{% for answer in question.answer_set.all %}
<div class="container my-1">
    <div class="row">
        <div class="col-lg-12">
            <a name="answer_{{answer.id}}"></a>
            <div class="card my-2">
                <div class="card-body">
                    <div id="content">
                        {{answer.content |mark }}
                    </div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left comment mr-1">
                            <div>modified at</div>
                            <div>{{answer.modify_date}}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left comment m1-1" style="margin-right: 10px;  background-color: #8b99a0;">
                            <div>{{question.author.username}}</div>
                            <div>{{answer.create_date}}</div>
                        </div>
                    </div>

                    {% if request.user == answer.author %}
                    <div class="my-2">
                        <a href="{% url 'community:answer_modify' answer.id %}"
                            class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                            data-uri="{% url 'community:answer_delete' answer.id %}">삭제</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor%}
<div class="container my-1">
    <div class="row">
        <div class="col-lg-12">
            <form action="{% url 'community:answer_create' question.id %}" method="post" class="my-2">
                {% csrf_token %}
                {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                    {% if field.errors %}
                    <strong>{{field.label}}</strong>
                    {{ field.errors }}
                    {% endif %}
                    {% endfor %}
                </div>
                {% endif %}
                <div class="form-group">
                    <textarea name="content" id="content" {% if not user.is_authenticated %}disabled {%endif%}
                        class="form-control" rows="5"></textarea>
                </div>
                <input type="submit" value="답변등록" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    $(document).ready(function () {
        $(".delete").on('click', function () {
            if (confirm("삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

templates/community/question_form.html
{% extends 'base.html' %}
{% block content %}
{% include "navbar.html" %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"> Posting
                <small>질문 등록</small>
            </h1>
            <ol class="breadcrumb" style="margin-top: -7px; margin-bottom: 2px;">
                <li><a href="{% url 'baseapp:index' %}">Home</a>
                </li>
                <li class="active"><a href="{% url 'community:index' %}" style="color: rgba(79, 76, 76, 0.749);">질문과 답변 리스트 </a></li>
            </ol> 
        </div>
    </div>
</div>

<div class="container">
    <div style="width:70%; margin-left:auto;margin-right:auto;">
    <form method="post" class="post-form my-3" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{form.as_p}} 폼 자동생성해주나 디자인문제 있음-->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{field.label}}</strong>
            {{ field.errors }}
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        
    <div class="form-group">
        <label for="suject">제목</label>
        <input type="text" class="form-control" name="subject" id="subject"
            value="{{form.subject.value|default_if_none:''}}">
    </div>
    <div class="form-group">
    <label for="content">내용</label>
    <textarea class="form-control" name="content" id="content" rows="7">
        {{form.content.value|default_if_none:''}}
    </textarea>
    </div>
    <div class="text-left">
        <label for="image_file" style="display:inline-block;">이미지 첨부:</label>
        <input type="file" name="image_file" id="image_file" value="{{form.image_file.value|default_if_none:''}}">
    </div>
    <div class="text-right">
        <button type="submit" class="btn btn-primary" float="right" style="text-align: center;">저장하기</button>
    </div>
    </form>
    </div>
</div>
{% endblock %}

templates/community/question_list.html
{% extends 'base.html' %}
{% load community_filter %}
{% block content %}
{% include "navbar.html" %}
<div class="container">
    <div class="row" >
        <div class="col-lg-12">
            <h1 class="page-header">Q&A
                <small>Questions & Answers </small>
            </h1>
            <ol class="breadcrumb" style="margin-top: -7px; margin-bottom: 2px;">
                <li><a href="{% url 'baseapp:index' %}">Home</a>
                </li>
                <li class="active"><a href="{% url 'community:index' %}" style="color: rgba(79, 76, 76, 0.749);">질문과 답변 리스트 </a></li>
            </ol> 
       </div>
    </div>
 
    <div class="justify-content-between">
     <div class="row">
        <div class="col-md-2">
            <select class="form-control so" style="float:left; margin-top: 3px; margin-bottom: 3px; height: 29px; width: 45%;">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
            </select>
        </div>
        <div class="col-md-4" style="float: right;margin-top: 2px;">
            <input type="text" class="form-control_1 kw" value="{{kw|default_if_none:''}}">
            <button type="button" id="btn_search" >검색</button>
        </div>
     </div>
    </div>
    <table class="table text-center">
        <thead>
            <tr class="text-center"  style="background-color: #146dbb; color:#fff;">
                <th class="text-center"> no</th>    
                <th class="text-center"> 제 목 </th>
                <th class="text-center"> 글쓴이 </th>
                <th class="text-center"> 작성일시 </th>
 <!--               <th class="text-center"> 첨부</th>   -->
            </tr>

            </thead>
        <tbody>
         {% if question_list %}
        {% for question in question_list %}
            <tr class="text-center">
                <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1}} </td>
                <td class="text-left">
         <a href="{% url 'community:detail' question.id %}"> 
                    {{question.subject}}
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small ml-2">
                    {{question.answer_set.count}}
                </span>
                {% endif %}
                </a></td>
                <td>{{ question.author.username }}</td>
                <td>{{question.create_date}} </td>
   <!--               <td >
                    {% if question.image_file %}
                    <span class="badge badge-secondary py-1"> O </span>
                    {%endif%}    -->            
                </td>
            </tr>
         {% endfor %}
    {% else %}
            <tr>
                <td colspan="3"> 등록된 질문이 없습니다.</td>
            </tr> 
    {% endif %}
        </tbody>
    </table>
    <div class="col-lg-2">
        <a href="{% url 'community:question_create' %}" class="btn btn-primary">
            질문 등록하기
        </a>
    </div>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
            {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" 
                    data-page="{{question_list.previous_page_number }}" href="#">
                    이전
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                    이전
                </a>
            </li>
            {% endif %}

        {%for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" 
                data-page="{{page_number }}" href="#">
                    {{page_number}}            
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{page_number}}" href="#">
                    {{page_number}}
                </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}

        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{question_list.next_page_number }}" href="#">
                다음
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                다음
            </a>
        </li>
        {% endif %}
    </ul>
    </div>
</div>
<form id="searchForm" method="get" action="{% url 'community:index'%}">
    <input type="hidden" id="kw" name="kw" value="{{kw|default_if_none:''}}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script%}
<script type="text/javascript">
    $(document).ready(function(){
        $(".page-link").on('click', function(){
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
        });
        $("#btn_search").on('click', function(){
            $("#kw").val($(".kw").val());
            $("#page").val(1);
            $("#searchForm").submit();
        });
        $(".so").on('change', function() {
            $("#so").val($(this).val());
            $("#page").val(1);
            $("#searchForm").submit();
       });
    });
</script>
{% endblock %}