baseapp/urls.py
from django.urls import path
from . import views

app_name='baseapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('baseapp/about/',views.about, name='about'),
    path('baseapp/portfolio_1/',views.portfolio_1, name='portfolio_1'),
    path('baseapp/portfolio_2/',views.portfolio_2, name='portfolio_2'),
    path('baseapp/portfolio_3/',views.portfolio_3, name='portfolio_3'),
    path('baseapp/portfolio_4/',views.portfolio_4, name='portfolio_4'),
    path('baseapp/portfolio_0/',views.portfolio_0, name='portfolio_0'),
    path('baseapp/faq/',views.faq, name='faq'),

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name ='common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

community/urls.py
from django.urls import path
from . import views

app_name='community'

urlpatterns = [
    path("", views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/',views.answer_create, name='answer_create'),
    path('question/create/',views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer, name='comment_delete_answer'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from community import views
from django.conf.urls.static import static
from django.conf import settings


# from community import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("community/", include('community.urls')),
    path('common/', include('common.urls')),
    path('qq', views.index, name='index1'),
    path('', include('baseapp.urls'), name='index'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email=forms.EmailField(label="이메일")

    class Meta:
        model=User
        fields=("username", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render,redirect
from common.forms import UserForm

# Create your views here.

def signup(request):
    if request.method=="POST":
        form=UserForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            raw_password=form.cleaned_data.get('password1')
            user=authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('baseapp:index')
    else:
        form=UserForm()
    return render(request, 'common/signup.html', {'form':form})

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
{% include "navbar.html" %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"> Login
                <small>로그인</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url 'community:index' %}">Home</a>
                </li>
                <li class="active" >Login</li>
            </ol>
        </div>
    </div>
</div>
<div class="container my-3">
    <div class="row justify-content-between">
         <div class="col-8 text-right">
            <span>
                또는 <a href="{% url 'common:signup' %}">회원가입 하십시요</a>
            </span>
        </div>
    </div>

  <div style="width:40%; margin-left:auto;margin-right:auto;">  
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}">
        {% include "form_errors.html" %}
    <div class="form-group">
        <label for="username">사용자 ID</label>
        <input type="text" class="form-control" name="username" id="username"
            value="{{form.username.value|default_if_none:''}}">
    </div>
    <div class="form-group">
    <label for="password">비밀번호</label>
    <input type="password" class="form-control" name="password" id="password"
            value="{{form.password.value|default_if_none:''}}">
    </div>
    <div style="text-align: center;">
        <button type="submit" class="btn btn-primary">로그인</button></div>
    </form>
  </div>
</div>
{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
{% include "navbar.html" %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"> Signup
                <small>회원가입</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url 'baseapp:index' %}">Home</a>
                </li>
                <li class="active" >Signup</li>
            </ol>
        </div>
    </div>
</div>

<div class="container my-3">
    <div class="row my-3">
        <div class="col-12 text-right">
            <span>
                또는 <a href="{% url 'common:login' %}">로그인 하십시요</a>
            </span>
        </div>
    </div>
  <div style="width:40%; margin-left:auto;margin-right:auto;">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
    <div class="form-group">
        <label for="username">사용자 이름</label>
        <input type="text" class="form-control" name="username" id="username"
            value="{{form.username.value|default_if_none:''}}">
    </div>
    <div class="form-group">
    <label for="password1">비밀번호</label>
    <input type="password" class="form-control" name="password1" id="password1"
            value="{{form.password1.value|default_if_none:''}}">
    </div>
    <div class="form-group">
        <label for="password2">비밀번호 확인</label>
        <input type="password" class="form-control" name="password2" id="password2"
                value="{{form.password2.value|default_if_none:''}}">
    </div>
    <div class="form-group">
        <label for="email">이메일</label>
        <input type="text" class="form-control" name="email" id="email"
                value="{{form.email.value|default_if_none:''}}">
    </div> 
    <div style="text-align: center;">
        <button type="submit" class="btn btn-primary">회원가입</button>
    </form></div>
  </div>
</div>
{% endblock %}