baseapp/urls.py
from django.urls import path
from . import views

app_name='baseapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('baseapp/about/',views.about, name='about'),
    path('baseapp/portfolio_1/',views.portfolio_1, name='portfolio_1'),
    path('baseapp/portfolio_2/',views.portfolio_2, name='portfolio_2'),
    path('baseapp/portfolio_3/',views.portfolio_3, name='portfolio_3'),
    path('baseapp/portfolio_4/',views.portfolio_4, name='portfolio_4'),
    path('baseapp/portfolio_0/',views.portfolio_0, name='portfolio_0'),
    path('baseapp/faq/',views.faq, name='faq'),

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name ='common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

community/urls.py
from django.urls import path
from . import views

app_name='community'

urlpatterns = [
    path("", views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/',views.answer_create, name='answer_create'),
    path('question/create/',views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer, name='comment_delete_answer'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from community import views
from django.conf.urls.static import static
from django.conf import settings


# from community import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("community/", include('community.urls')),
    path('common/', include('common.urls')),
    path('qq', views.index, name='index1'),
    path('', include('baseapp.urls'), name='index'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SUNBIZ 썬비즈입니다!</title>
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/modern-business.css' %}" rel="stylesheet">

</head>
<body>  
    {% block content %}
    {% endblock %}
    <script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/modern-business.js' %}"></script>

    {% block script %}
    {% endblock %}
    <div class="container">
        <hr>
            <div class="row">
                <div class="col-12">
                    <p>Copyright &copy; Company SUNBIZ 2023</p>
                </div>
            </div>
    </div>
</body>
</html>

templates/form_errors.html
 
{% if form.errors %}
{% for field in form %}
    {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{field.label}}</strong>
            {{error}}
        </div>
    {% endfor %}
{% endfor%}
{% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <strong> {{error}}</strong>
    </div>
{% endfor %}
{% endif %}

templates/full-width.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Full Width Page - Modern Business - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="css/modern-business.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Modern Business</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="about.html">About</a>
                    </li>
                    <li><a href="services.html">Services</a>
                    </li>
                    <li><a href="contact.php">Contact</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="portfolio-1-col.html">1 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-2-col.html">2 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-3-col.html">3 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-4-col.html">4 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-item.html">Single Portfolio Item</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="blog-home-1.html">Blog Home 1</a>
                            </li>
                            <li><a href="blog-home-2.html">Blog Home 2</a>
                            </li>
                            <li><a href="blog-post.html">Blog Post</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="active"><a href="full-width.html">Full Width Page</a>
                            </li>
                            <li><a href="sidebar.html">Sidebar Page</a>
                            </li>
                            <li><a href="faq.html">FAQ</a>
                            </li>
                            <li><a href="404.html">404</a>
                            </li>
                            <li><a href="pricing.html">Pricing Table</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">Full Width Page
                    <small>For Deeper Customization</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li class="active">Full Width Page</li>
                </ol>
            </div>

        </div>

        <div class="row">

            <div class="col-lg-12">
                <p>This page features a page header, breadcrumbs, and the footer but that's it. Use this as a template for completely custom pages you wish to add to your site.</p>
                <p>Be sure to read over and understand all of the Bootstrap 3 components at <a href="http://getbootstrap.com">http://getbootstrap.com</a> to get the most out of any Start Bootstrap template.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam placerat nunc ut tellus tristique, non posuere neque iaculis. Fusce aliquet dui ut felis rhoncus, vitae molestie mauris auctor. Donec pellentesque feugiat leo a adipiscing. Pellentesque quis tristique eros, sed rutrum mauris.</p>
            </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/modern-business.js"></script>

</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
{%load static %}
{% include "navbar.html" %}

<div id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="fill" style="background-image:url('./static/images/bg_1.jpg');"></div>
            <div class="carousel-caption">
                <h1>Protection of the Environment <br>
                    썬비즈에 오신 것을 환영합니다.<br><br></h1>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('./static/images/bg_3.jpg');"></div>
            <div class="carousel-caption">
                    <h1>자연을 생각합니다.<br>
                        안전한 미래를 창조합니다.<br><br></h1>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('./static/images/bg_4.jpg');"></div>
            <div class="carousel-caption">
                <h1>Create the Value, Shape the Future
                    SUNBIZ
                    <a href="{% url 'baseapp:index' %}">http://sunbiz.com</a><br><br>
                </h1>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</div>
<div class="section" style="margin:10px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4">
                <h3><i class="fa fa-check-circle"></i> Sunbiz now start!</h3>
                <p>Use the work on this with GIS and learn how it can be used to better understand our natural environment.  by <a  href="{% url 'baseapp:index' %}">Sunbiz.com</a> GIS for Biology, Ecology and Environmental Science work.The provides a very brief introduction to what GIS is and why it is a useful tool for biologists to use in their research. Start <a href="{% url 'baseapp:index' %}" >Sunbiz!</a></p>
            </div>
            <div class="col-lg-4 col-md-4">
                <h3><i class="fa fa-pencil"></i> GIS, BIO and Data </h3>
                <p>Spatial data can help you understand patterns and trends in biology and ecology. You can see some free themes over at <a href="http://www.hangaramit.com/">hangaram.IT.school</a>, or come up with your own using</a>! Thisconnects with with a wide range of data and other spatial resources in the areas of Biology.</p>
            </div>
            <div class="col-lg-4 col-md-4">
                <h3><i class="fa fa-folder-open"></i> Biology, Ecology and... </h3>
                <p> Biotechnology! <a href="https://www.kei.re.kr/kor/"> KEI(www.kei.re.kr)</a>! From tracking animals to monitoring habitats, GIS is becoming an indispensable skillset for biologists and ecologists. Explore the habitats and diversity of our natural world with these ready to use it. Start work! Let's study!</p>
            </div>
        </div>
    </div>
</div>
<!-- /.section -->
<div class="section-colored text-center">
    <div class="text-center" style="color: rgba(140, 140, 143, 0.787);">
        <p><h3>Spatial data can help you understand patterns and trends in biology, ecology and biotechnology.</h3> </p>
        <p><h2 style="font-family: 'Times New Roman', Times;  color:rgb(34, 93, 157) ;">Display Some Work on the our Portfolio!</h2></p>
    </div>
</div><br>
<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="#">
                    <img class="img-responsive img-home-portfolio" src="{% static 'images/07.png' %}"
                        style="width:350px;height:230px">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="#">
                    <img class="img-responsive img-home-portfolio" src="{% static 'images/37.png' %}"
                        style="width:350px;height:230px">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="#">
                    <img class="img-responsive img-home-portfolio" src="{% static 'images/13.jpg' %}"
                        style="width:350px;height:230px">
                </a>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="#">
                    <img class="img-responsive img-home-portfolio" src="{% static 'images/33.png' %}"
                        style="width:350px;height:230px">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="#">
                    <img class="img-responsive img-home-portfolio" src="{% static 'images/19.png' %}"
                        style="width:350px;height:230px">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="#">
                    <img class="img-responsive img-home-portfolio" src="{% static 'images/03.png' %}"
                        style="width:350px;height:230px">
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/navbar.html
{%load static %}
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'baseapp:index' %}">SUNBIZ 썬비즈</a>
        </div>

        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'baseapp:about' %}">About us</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Work Areas <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'baseapp:portfolio_1' %}">GIS</a>
                        </li>
                        <li><a href="{% url 'baseapp:portfolio_2' %}">빅데이터</a>
                        </li>
                        <li><a href="{% url 'baseapp:portfolio_3' %}">바이오생명</a>
                        </li>
                        <li><a href="{% url 'baseapp:portfolio_4' %}">환경평가</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Project<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href=#">수주리스트</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Services<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">철새정보</a>
                        </li>
                        <li><a href="#">물환경</a>
                        </li>
                    </ul>
                </li>                   
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Community<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'baseapp:faq' %}">공지사항</a>
                        </li>
                        <li><a href="{% url 'community:index' %}">질문과 답변</a>
                        </li>
                        <li><a href="#">자유게시판</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">
                    {{user.username}} (로그아웃)
                    </a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
             </ul>
        </div>
       
 </div>
</nav>

templates/sidebar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sidebar Page - Modern Business - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="css/modern-business.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                <a class="navbar-brand" href="index.html">Modern Business</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="about.html">About</a>
                    </li>
                    <li><a href="services.html">Services</a>
                    </li>
                    <li><a href="contact.php">Contact</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="portfolio-1-col.html">1 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-2-col.html">2 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-3-col.html">3 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-4-col.html">4 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-item.html">Single Portfolio Item</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="blog-home-1.html">Blog Home 1</a>
                            </li>
                            <li><a href="blog-home-2.html">Blog Home 2</a>
                            </li>
                            <li><a href="blog-post.html">Blog Post</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="full-width.html">Full Width Page</a>
                            </li>
                            <li class="active"><a href="sidebar.html">Sidebar Page</a>
                            </li>
                            <li><a href="faq.html">FAQ</a>
                            </li>
                            <li><a href="404.html">404</a>
                            </li>
                            <li><a href="pricing.html">Pricing Table</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->

    <div class="container">

        <div class="row">
            <div class="col-md-3 col-sm-4 sidebar">
                <ul class="nav nav-stacked nav-pills">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li><a href="about.html">About</a>
                    </li>
                    <li><a href="services.html">Services</a>
                    </li>
                    <li><a href="contact.php">Contact</a>
                    </li>
                    <li class="disabled"><a href="#">Portfolio</a>
                    </li>
                    <li><a href="portfolio-1-col.html">1 Column Portfolio</a>
                    </li>
                    <li><a href="portfolio-2-col.html">2 Column Portfolio</a>
                    </li>
                    <li><a href="portfolio-3-col.html">3 Column Portfolio</a>
                    </li>
                    <li><a href="portfolio-4-col.html">4 Column Portfolio</a>
                    </li>
                    <li><a href="portfolio-item.html">Single Portfolio Item</a>
                    </li>
                    <li class="disabled"><a href="#">Blog</a>
                    </li>
                    <li><a href="blog-home-1.html">Blog Home 1</a>
                    </li>
                    <li><a href="blog-home-2.html">Blog Home 2</a>
                    </li>
                    <li><a href="blog-post.html">Blog Post</a>
                    </li>
                    <li class="disabled"><a href="#">Blog</a>
                    </li>
                    <li><a href="full-width.html">Full Width Page</a>
                    </li>
                    <li class="active"><a href="sidebar.html">Sidebar Page</a>
                    </li>
                    <li><a href="faq.html">FAQ</a>
                    </li>
                    <li><a href="404.html">404</a>
                    </li>
                    <li><a href="pricing.html">Pricing Table</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-9 col-sm-8">
                <h1 class="page-header">Sidebar Page
                    <small>For Deeper Customization</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li class="active">Full Width Page</li>
                </ol>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam placerat nunc ut tellus tristique, non posuere neque iaculis. Fusce aliquet dui ut felis rhoncus, vitae molestie mauris auctor. Donec pellentesque feugiat leo a adipiscing. Pellentesque quis tristique eros, sed rutrum mauris.</p>
            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/modern-business.js"></script>

</body>

</html>